# Generated by Django 4.2.6 on 2023-12-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nonCSVPasswords',
            new_name='NonCSV',
        ),
    ]
